name: Require Label on Pull Request

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - develop

jobs:
  run_if:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Check for required label
        run: |
          #!/bin/bash
          set -e

          # Get all labels from the pull request
          LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

          # Check if the required label is present
          if echo "$LABELS" | grep -q "${{ vars.REQUIRED_LABEL }}"; then
            echo "Required label '${{ vars.REQUIRED_LABEL }}' is present."
            exit 0
          else
            echo "Error: Required label '${{ vars.REQUIRED_LABEL }}' is missing."
            exit 1
          fi
