name: Require Label on Pull Request

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - develop

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get develop branch label
        run: |
          DEVELOP_LABEL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/labels" | \
            jq -r '.[] | select(.name | startswith("develop-")) | .name')
          echo "REQUIRED_LABEL=$DEVELOP_LABEL" >> $GITHUB_ENV
      - name: Check for required label
        run: |
          #!/bin/bash
          set -e

          # Get all labels from the pull request
          LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

          # Check if the required label is present
          if echo "$LABELS" | grep -q "^$REQUIRED_LABEL$"; then
            echo "Required label '${{ vars.REQUIRED_LABEL }}' is present."
            exit 0
          else
            echo "Error: Required label '$REQUIRED_LABEL' is missing."
            exit 1
          fi
