name: Require Label on Pull Request

on:
  pull_request:
    types: 
      - opened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - develop

jobs:
  check-label:
    if: ${{ !startsWith(github.head_ref, 'hotfix/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check for required label
        env:
          RELEASE_LABEL: ${{ vars.RELEASE_LABEL }}
        run: |
          #!/bin/bash
          set -e

          LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")

          if echo "$LABELS" | grep -q "$RELEASE_LABEL"; then
            echo "Required label '$RELEASE_LABEL' is present."
            exit 0
          else
            echo "Error: Required label $RELEASE_LABEL is missing."
            exit 1
          fi
