name: Create a new release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  update-version:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get the latest release tag
        run: |
          LATEST_RELEASE=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest)
          LATEST_TAG=$(echo $LATEST_RELEASE | jq -r .tag_name)
          LATEST_TAG=${LATEST_TAG#v}
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Generate a tag for minor update
        if: startsWith(github.head_ref, 'develop')
        run: |
          # Split the latest tag into its components
          IFS='.' read -r -a TAG_PARTS <<< "$LATEST_TAG"

          # Increment the minor version
          NEW_MINOR=$((TAG_PARTS[1] + 1))

          # Construct the new tag
          NEW_TAG="${TAG_PARTS[0]}.$NEW_MINOR.0"

          # Output the new tag
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Generate a tag for hotfix update
        if: startsWith(github.head_ref, 'hotfix')
        run: |
            # Split the latest tag into its components
            IFS='.' read -r -a TAG_PARTS <<< "$LATEST_TAG"

            # Increment the patch version
            NEW_PATCH=$((TAG_PARTS[2] + 1))

            # Construct the new tag
            NEW_TAG="${TAG_PARTS[0]}.${TAG_PARTS[1]}.$NEW_PATCH"

            # Output the new tag
            echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
    
      - name: Create a new release
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{\"tag_name\":\"${{ env.NEW_TAG }}\"}"
          
          echo "Cretaed a new release: ${{ env.NEW_TAG }}"
  
      - name: Create a new pull request
        run: |
          

