name: Increment the release label

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  increment-label:
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'develop')
    runs-on: ubuntu-latest
    env:
      LABEL_NAME: RELEASE_LABEL
      RELEASE_LABEL: ${{ vars.RELEASE_LABEL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update environment variable
        run: |
          CURRENT_VALUE=$RELEASE_LABEL
          CURRENT_NUMBER=${CURRENT_VALUE#R}
          NEW_NUMBER=$((CURRENT_NUMBER + 1))

          # R25の次はR1にする
          if [ $NEW_NUMBER -gt 25 ]; then
            NEW_NUMBER=1
          fi

          NEW_VALUE="R$NEW_NUMBER"
          echo "NEW_VALUE=$NEW_VALUE" >> $GITHUB_ENV
      - name: Remove the current label
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/labels/$RELEASE_LABEL
          echo "Removed the current label"
      - name: Update the release label
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/$LABEL_NAME \
            -d "{\"name\":\"$LABEL_NAME\",\"value\":\"${{ env.NEW_VALUE }}\"}"

          echo "Environment variable $LABEL_NAME updated to ${{ env.NEW_VALUE }}"
