name: Update Environment Variable on Main Branch

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'develop')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update environment variable
        env: 
          OWNER: caesar1231
        run: |
          # Get the current REQUIRED_LABEL value
          CURRENT_VALUE=${{ vars.REQUIRED_LABEL }}

          # Extract the number after 'R'
          CURRENT_NUMBER=${CURRENT_VALUE#R}

          # Increment the number
          NEW_NUMBER=$((CURRENT_NUMBER + 1))

          # Reset to 1 if it reaches 26
          if [ $NEW_NUMBER -gt 25 ]; then
            NEW_NUMBER=1
          fi

          # Create the new value
          NEW_VALUE="R$NEW_NUMBER"

          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/caesar1231/test/actions/variables/REQUIRED_LABEL

          # Update the REQUIRED_LABEL variable
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/caesar1231/test/actions/variables" \
            -d '{"name":"REQUIRED_LABEL","value":"$NEW_VALUE"}'

          echo "Environment variable REQUIRED_LABEL updated to $NEW_VALUE"
