name: Update Environment Variable on Main Branch

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  increment_label:
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'develop')
    runs-on: ubuntu-latest
    env:
      LABEL_NAME: RELEASE_LABEL
      RELEASE_LABEL: ${{ vars.RELEASE_LABEL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update environment variable
        run: |
          # Get the current REQUIRED_LABEL value
          CURRENT_VALUE=$RELEASE_LABEL

          # Extract the number after 'R'
          CURRENT_NUMBER=${CURRENT_VALUE#R}

          # Increment the number
          NEW_NUMBER=$((CURRENT_NUMBER + 1))

          # Reset to 1 if it reaches 26
          if [ $NEW_NUMBER -gt 25 ]; then
            NEW_NUMBER=1
          fi

          # Create the new value
          NEW_VALUE="R$NEW_NUMBER"
          echo "NEW_VALUE=$NEW_VALUE" >> $GITHUB_ENV
      - name: remove current label
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/labels/$RELEASE_LABEL
          echo "removed the current label"
      - name: update the label
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/$LABEL_NAME \
            -d "{\"name\":\"REQUIRED_LABEL\",\"value\":\"${{ env.NEW_VALUE }}\"}"

          echo "Environment variable REQUIRED_LABEL updated to ${{ env.NEW_VALUE }}"
